In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dense
from tensorflow.keras.optimizers import Adam
import pandas as pd
import numpy as np
import sklearn
from sklearn import svm
from sklearn.preprocessing import StandardScaler

In [ ]:
# Defining  column names
column_names = ['JointAngle1', 'JointAngle2', 'JointAngle3', 'JointAngle4', 'JointAngle5', 'JointAngle6',
                'X_Position', 'Y_Position', 'Z_Position', 'RotationElement1', 'RotationElement2', 'RotationElement3']

# Loading of the dataset with specified column names
data = pd.read_csv('/content/random.csv', names=column_names)

In [ ]:
data.head()

JointAngle1  JointAngle2  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401    -0.516810      0.88886   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    -0.664540      0.05001   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    -2.069200     -1.97410   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    -0.716570     -0.10199   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333     0.069533      0.82531   

                                                    JointAngle3  JointAngle4  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401      4.00790      0.79437   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015      3.95280     -0.20176   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392      0.96334      0.44964   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264      3.22820      0.51233   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333      1.15990     -0.49078   

                                                    JointAngle5  JointAngle6  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401      0.56086    -0.233270   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015     -0.96459    -0.169890   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392     -0.88847     0.091861   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264     -0.67524     0.530630   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333      0.64548    -0.585240   

                                                    X_Position  Y_Position  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401   -0.576760     0.81691   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    0.417650    -0.24162   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    0.034581     0.12008   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    0.709880     0.68071   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333    0.173550     0.73065   

                                                    Z_Position  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401    0.000052   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    0.875890   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    0.992160   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    0.180820   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333    0.660320   

                                                    RotationElement1  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401           0.19059   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015          -0.88593   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          -0.89254   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264          -0.48330   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333           0.85383   

                                                    RotationElement2  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401           0.13450   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015           0.10577   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          -0.44294   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264           0.28404   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333           0.22251   

                                                    RotationElement3  
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401          0.972410  
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015          0.451600  
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          0.084718  
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264          0.828090  
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333         -0.470610

In [ ]:
data.tail()

JointAngle1  JointAngle2  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664     -0.15121     -0.37805   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600     -1.91690     -0.00922   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769     -0.40969     -0.53897   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760     -0.13659     -0.37310   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732     -0.32883     -1.01910   

                                                     JointAngle3  JointAngle4  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664     4.089800     -0.86960   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600     1.868700     -0.16102   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769     3.220800     -0.64147   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760     4.219800      0.78530   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732     0.041893     -0.33901   

                                                     JointAngle5  JointAngle6  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664     0.479380     -0.11830   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600    -0.613850     -0.77282   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769     0.060809      0.76473   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760     0.352870      0.50872   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732     0.434290      0.83454   

                                                     X_Position  Y_Position  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664    -0.40197    -0.82645   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600    -0.48866    -0.63074   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769    -0.67181     0.43676   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760    -0.47001     0.87462   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732     0.53621    -0.63968   

                                                     Z_Position  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664    -0.39421   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600     0.60281   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769    -0.59826   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760     0.11888   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732     0.55071   

                                                     RotationElement1  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664          -0.28674   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600          -0.85749   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769          -0.37038   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760          -0.40299   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732           0.77301   

                                                     RotationElement2  \
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664          -0.29525   
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600           0.47471   
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769          -0.89752   
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760          -0.33246   
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732           0.63419   

                                                     RotationElement3  
-1.26700 2.06690  0.65550 -5.2000  0.42211 -0.21664          0.911380  
 0.25935 1.62400  2.99360 -4.3409 -0.81603  5.04600         -0.198400  
 2.54540 1.13350  2.32420  1.8399 -1.73760  0.97769         -0.239320  
-0.73902 1.40480  1.81810 -1.5794 -0.54356  5.89760          0.852690  
-2.10950 0.69958 -0.56411 -2.7943  1.68220 -0.53732         -0.016014

In [ ]:
X = data.drop(columns=['X_Position', 'Y_Position','Z_Position',])
Y = data[['X_Position', 'Y_Position', 'Z_Position']]

In [ ]:
X.head()

JointAngle1  JointAngle2  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401    -0.516810      0.88886   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    -0.664540      0.05001   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    -2.069200     -1.97410   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    -0.716570     -0.10199   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333     0.069533      0.82531   

                                                    JointAngle3  JointAngle4  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401      4.00790      0.79437   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015      3.95280     -0.20176   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392      0.96334      0.44964   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264      3.22820      0.51233   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333      1.15990     -0.49078   

                                                    JointAngle5  JointAngle6  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401      0.56086    -0.233270   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015     -0.96459    -0.169890   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392     -0.88847     0.091861   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264     -0.67524     0.530630   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333      0.64548    -0.585240   

                                                    RotationElement1  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401           0.19059   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015          -0.88593   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          -0.89254   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264          -0.48330   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333           0.85383   

                                                    RotationElement2  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401           0.13450   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015           0.10577   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          -0.44294   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264           0.28404   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333           0.22251   

                                                    RotationElement3  
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401          0.972410  
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015          0.451600  
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392          0.084718  
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264          0.828090  
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333         -0.470610

In [ ]:
Y.head()

X_Position  Y_Position  \
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401   -0.576760     0.81691   
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    0.417650    -0.24162   
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    0.034581     0.12008   
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    0.709880     0.68071   
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333    0.173550     0.73065   

                                                    Z_Position  
-0.88254 2.1659  1.25370  3.82890  0.37542 -5.4401    0.000052  
 0.63053 1.6022  1.61690  2.36320 -1.04630 -1.7015    0.875890  
 0.85788 2.5143  2.47530  0.85839 -0.53443 -5.4392    0.992160  
 0.68397 2.8924 -0.15305 -3.94820 -0.81534  5.4264    0.180820  
 2.24920 2.5581 -1.10640  2.13620  1.87980  2.7333    0.660320

In [ ]:
# Create a StandardScaler object
scaler = StandardScaler()

In [ ]:
X_scaled = scaler.fit_transform(X)
Y_scaled = scaler.fit_transform(Y)

In [ ]:
print(X_scaled)

[[-0.41884726  0.6585858   1.42120276 ...  0.33867712  0.22694369
   1.55316382]
 [-0.53354971  0.04455869  1.37926961 ... -1.53773351  0.17735593
   0.64429407]
 [-1.62417412 -1.43706308 -0.89582058 ... -1.54925497 -0.76971332
   0.00404532]
 ...
 [-0.33567576 -0.38656689  0.8221904  ... -0.63911249 -1.55431491
  -0.56143603]
 [-0.1236319  -0.26515224  1.58246653 ... -0.69595282 -0.57902569
   1.34423948]
 [-0.27289338 -0.7380157  -1.597076   ...  1.3538548   1.08940479
  -0.17174291]]


In [ ]:
print(Y_scaled)

[[-1.00433649  1.4170759  -0.02485037]
 [ 0.70032948 -0.44121524  1.48870839]
 [ 0.04365398  0.19376337  1.68963776]
 ...
 [-1.16727582  0.74970759 -1.05881055]
 [-0.82134045  1.51838808  0.1804987 ]
 [ 0.9035708  -1.14002526  0.92675594]]


In [ ]:
mean_values = scaler.mean_
scale_values = scaler.scale_

print("Mean Values:", mean_values)
print("Scale Values:", scale_values)

Mean Values: [0.00911563 0.00970745 0.01443243]
Scale Values: [0.58334595 0.56962549 0.57866106]


# feed dataset into deep neural network

In [ ]:
# Define your neural network model with a name
model = tf.keras.Sequential(name="my_end_effector_prediction")

# Determine the input size based on the number of features in your dataset
input_size = X_scaled.shape[1]
print("Input size:", input_size)

# Add layers to the model
model.add(tf.keras.layers.Dense(units=128, input_shape=(input_size,), activation='relu'))
model.add(tf.keras.layers.Dropout(0.3))  # Adjust dropout rate
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.3))  # Adjust dropout rate
model.add(tf.keras.layers.Dense(units=3, activation='linear'))  # Use linear activation for regression

# Compile the model
model.compile(optimizer='adam',
              loss='mean_squared_error',  # Using mean squared error for regression
              metrics=['mae'])  # Monitor mean absolute error

# Fit the model to the training data
history = model.fit(X_scaled, Y_scaled, epochs=35, batch_size=30, validation_split=0.2)  # Adjust epochs and batch size

# Print the training history
print(history.history.keys())

# Print the final training and validation accuracy
train_mae = history.history['mae'][-1]
val_mae = history.history['val_mae'][-1]
print("Final training MAE:", train_mae)
print("Final validation MAE:", val_mae)

# Save the model to a file
model.save('my_end_effector_prediction')

Input size: 9
Epoch 1/35
134/134 [==============================] - 1s 4ms/step - loss: 0.5608 - mae: 0.6083 - val_loss: 0.0807 - val_mae: 0.2286
Epoch 2/35
134/134 [==============================] - 0s 3ms/step - loss: 0.2075 - mae: 0.3628 - val_loss: 0.0359 - val_mae: 0.1559
Epoch 3/35
134/134 [==============================] - 0s 3ms/step - loss: 0.1580 - mae: 0.3181 - val_loss: 0.0239 - val_mae: 0.1281
Epoch 4/35
134/134 [==============================] - 0s 2ms/step - loss: 0.1386 - mae: 0.2964 - val_loss: 0.0187 - val_mae: 0.1139
Epoch 5/35
134/134 [==============================] - 0s 3ms/step - loss: 0.1215 - mae: 0.2776 - val_loss: 0.0198 - val_mae: 0.1177
Epoch 6/35
134/134 [==============================] - 0s 3ms/step - loss: 0.1132 - mae: 0.2676 - val_loss: 0.0167 - val_mae: 0.1080
Epoch 7/35
134/134 [==============================] - 0s 3ms/step - loss: 0.1064 - mae: 0.2596 - val_loss: 0.0149 - val_mae: 0.1033
Epoch 8/35
134/134 [==============================] - 0s 3ms/s

# predicting output based on user input

In [ ]:
# Load the trained model
model = tf.keras.models.load_model('my_end_effector_prediction')

# Function to preprocess user input
def preprocess_input(input_data):
    # Perform any necessary preprocessing, such as scaling or normalization
    # Make sure to apply the same preprocessing steps used during training

    # If data is already preprocessed
    scaled_input = input_data
    return scaled_input

# Function to predict end-effector positions
def predict_end_effector_position(input_data):
    # Preprocess the input data
    scaled_input = preprocess_input(input_data)

    # Make predictions using the trained model
    predictions = model.predict(scaled_input)

    # Return the predicted end-effector positions
    return predictions

# Testing your model

In [ ]:
# input joint angles and rotation effect to predict your end-effector postions
if __name__ == "__main__":
    # Adjusting  the input shape to match the model's input size (9 features)
    user_input =np.array([[-1.51E+00	,-7.63E-01,1.85E+00,-8.17E-01,9.12E-01,2.32E+00, 0.19059, 0.1345, 0.97241]])


    # Predict end-effector positions
    predicted_positions = predict_end_effector_position(user_input)

    # Print the predicted positions
    print("Predicted end-effector positions based on your inputs :")
    print(predicted_positions)

1/1 [==============================] - 0s 26ms/step
Predicted end-effector positions based on your inputs :
[[-0.12706406 -0.41563463  0.17548835]]
